// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeDfZy9vmN2ET1hGJgt2LI06-Ff594nso',
    appId: '1:500183975383:web:10770cd4e116377abe7792',
    messagingSenderId: '500183975383',
    projectId: 'kodal-ecommerce-flutter',
    authDomain: 'kodal-ecommerce-flutter.firebaseapp.com',
    storageBucket: 'kodal-ecommerce-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVoRCMrklyGSVt8-jdBov6fi9ZvHW_X_c',
    appId: '1:500183975383:android:c90a231b81c78c11be7792',
    messagingSenderId: '500183975383',
    projectId: 'kodal-ecommerce-flutter',
    storageBucket: 'kodal-ecommerce-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIg5hfyZPUFTdGjbBlZ-Pmt3rod-w8BT4',
    appId: '1:500183975383:ios:21bc478efe32d8ddbe7792',
    messagingSenderId: '500183975383',
    projectId: 'kodal-ecommerce-flutter',
    storageBucket: 'kodal-ecommerce-flutter.firebasestorage.app',
    iosBundleId: 'com.burakkodaloglu.kodalECommerce',
  );
}
